### ISSUE TITLE
Event names

### ISSUE THREAD

**Issue by drspaniel** [hoodiehq/hoodie-client-connection-status#14]
I would prefer `disconnect` and `reconnect` to `disconnected` and `reconnected`.
I don't have any strong evidence, it just feels more natural to me and I have the impression it's the more common way to name events.

**Comment by gr2m** [comment]
That's a very good point! In fact, I asked the question about event name conventions a while ago myself: http://stackoverflow.com/questions/11450397/javascript-event-naming-conventions

Yeah, I'm in favor for present tense, as all hoodie events are.

**Comment by Charlotteis** [comment]
Agree!

**Comment by gr2m** [comment]
All right, let's do it :) I've set the bug label, let’s fix it :)

**Comment by gr2m** [comment]
fixed via #16 (ac90f9e)
