### ISSUE TITLE
Implement connectionStatus.isChecking

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-connection-status#22]
Requires up for #13. 

```js
connectionStatus.isChecking
```

_Read-only_ like `connectionStatus.ok`. Returns `true` if connection is checked continuously, otherwise `false`. The state is persisted in cache.

--- 

- [x] claim this issue (comment below)
- [x] start a pull request
- [x] write tests
- [x] implement
- [ ] update README
- [ ] review & merge

Ping me in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/gr2m/) if you have any questions

**Comment by jennazee** [comment]
Will take once #13 / #19 is merged

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/hoodie-client-connection-status/pull/26
