### ISSUE TITLE
Implement options.interval.connected & options.interval.disconnected

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-connection-status#24]
The code below should continuously check for connection status. If connected, check every 30s, if disconnected, check every 3s.

```js
new ConnectionStatus({
  interval: {
    connected: 30000,
    disconnected: 3000,
  }
})
```

As part of this issue, the use of the internal `state.interval` variable must be refactored to be called `state.checkTimeout`, so it does not interfere with `state.interval` being set from the Constructor options.

---

**Working on your first Pull Request?** You can learn how from this *free* series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) 

---

- [x] claim this issue (@nathanstilwell)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-client-connection-status#testing) and make sure that all tests pass: 
- [x] Find & Replace all `state.interval` with `state.checkTimeout`
- [x] commit with `refactor: state.interval → state.checkTimeout`
- [x] start a pull request
- [x] amend [tests/unit/utils-parse-options.js](https://github.com/hoodiehq/hoodie-client-connection-status/blob/master/tests/unit/utils-parse-options.js) to make sure it always returns `{ interval: { connected, disconnected } }`. If `options.interval` is a number, set both connected & disconnected to that number. Make sure the new test fails
- [x] commit change with `test(unit): options.interval.connected / options.interval.disconnected` and push
- [x] implement the correct handling of `options.interval` in [lib/utils/parse-options.js](https://github.com/hoodiehq/hoodie-client-connection-status/blob/master/lib/utils/parse-options.js). Make sure the new tests pass
- [x] commit with `feat: options.interval.connected / options.interval.disconnected` and push
- [x] amend [tests/unit/reset.js](https://github.com/hoodiehq/hoodie-client-connection-status/blob/master/tests/unit/reset.js) to allow same options as constructor. Check that `state.interval` gets changed with the according option
- [x] commit with `test: reset(options)` and push
- [x] implement new options argument in reset method
- [x] commit with `feat: reset(options)` and push
- [x] amend [test/unit/start-checking.js](https://github.com/hoodiehq/hoodie-client-connection-status/blob/master/tests/unit/start-checking.js) to check that the timeout passed to `setTimeout` depends on whether `connection.ok`, that it defaults to `state.interval.connected` / `state.interval.disconnected` and that it can be overwritten with `options.interval` passed to `startChecking`. Make sure tests fail
- [x] commit with `test: startChecking with different intervals based on connection status` and push
- [x] implement accordingly in checkConnection method. Make sure tests pass
- [x] commit with `feat: startChecking with different intervals based on connection status` and push
- [x] update README (remove references to issue #24). Commit with `docs(README): removed references to #24`
- [ ] review & merge

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by FrauBienenstich** [comment]
@masadeus and I are working on this :)

**Comment by FrauBienenstich** [comment]
I forked the project here and created a new branch for it (very much WIP and not that much to be seen yet): https://github.com/FrauBienenstich/hoodie-client-connection-status/tree/connect_disconnect

**Comment by gr2m** [comment]
@FrauBienenstich start a Pull Request :) That will help with discussing it

**Comment by gr2m** [comment]
Hey @FrauBienenstich, are you still looking into this? Let me know if you have any questions, happy to help

**Comment by FrauBienenstich** [comment]
In theory yes! Although I haven't looked at it since the workshop, I am quite quite busy with looking for a new job atm. If this is not urgent or blocking anything I'd still love to give it a try though, if that is fine with you!

**Comment by gr2m** [comment]
absolutely :) Good luck with finding a new job, please give us a shout if we can help spread the word. If you find time again, feel free to ping me and we can pair remotely on it, if you like

**Comment by FrauBienenstich** [comment]
thanks gregor! :) i hope i will be able to get back to this very soon!

**Comment by gr2m** [comment]
@FrauBienenstich ping :)

**Comment by gr2m** [comment]
Hey @nathanstilwell, let me know if there is anything I can help you with :) we kinda sorta have a little deadline for this (next weekend), would be great to ship it soon

**Comment by nathanstilwell** [comment]
@gr2m Thanks for the head's up. I'll prioritize this and ping you on Slack if I need anything.

**Comment by gr2m** [comment]
released as https://github.com/hoodiehq/hoodie-client-connection-status/releases/tag/v2.6.0

Amazing work @nathanstilwell, thanks a lot! :clap:
