### ISSUE TITLE
Bring code coverage to 100%

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client-connection-status#4]
current status: [![Coverage Status](https://coveralls.io/repos/hoodiehq/hoodie-client-connection-status/badge.svg?branch=master)](https://coveralls.io/r/hoodiehq/hoodie-client-connection-status?branch=master)

```
npm run test:coverage

...

=============================== Coverage summary ===============================
Statements   : 98.15% ( 106/108 )
Branches     : 97.83% ( 45/46 )
Functions    : 93.33% ( 14/15 )
Lines        : 98.15% ( 106/108 )
================================================================================
```

---

- [x] claim this issue (@janecakemaster)
- [x] start a pull request
- [ ] write tests untit 100% coverage is reached
- [ ] review & merge

Ping me in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/gr2m/) if you have _any_ questions.

**Comment by gr2m** [comment]
Hey @janecakemaster, do you still wanna do this?

**Comment by janecakemaster** [comment]
oh yes! let me get to it this weekend :snowflake:

**Comment by gr2m** [comment]
yaaaay \o/ stay warm & safe, hope the blizzard won’t hit to hard!
